import React from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { AiCodeBlock } from '@/components/lightswind/ai-code-block';

const MarkdownRenderer = ({ content }) => {
  // Pre-process HTML tags that might be generated by the AI since we don't have rehype-raw
  const processedContent = content
    ? content
        .replace(/<br\s*\/?>/gi, '  \n') // convert <br> to markdown line break
        .replace(/<\/?b>/gi, '**')
        .replace(/<\/?strong>/gi, '**')
        .replace(/<\/?i>/gi, '*')
        .replace(/<\/?em>/gi, '*')
    : '';

  return (
    <ReactMarkdown
      remarkPlugins={[remarkGfm]}
      components={{
        code({ className, children, ...props }) {
          const match = /language-(\w+)/.exec(className || '');
          const code = String(children).replace(/\n$/, '');
          
          // In react-markdown v9+, 'inline' prop is removed.
          // We consider it inline if it doesn't have a language match and doesn't contain multiple lines.
          const isInline = !match && !code.includes('\n');

          if (isInline) {
            return (
              <code
                className="rounded-md bg-gray-100 dark:bg-gray-800 px-1.5 py-0.5 font-mono text-[0.92em] text-gray-800 dark:text-gray-200"
                {...props}
              >
                {children}
              </code>
            );
          }

          return (
            <div className="my-3">
              <AiCodeBlock
                code={code}
                language={match?.[1] || 'text'}
                filename={match?.[1] ? `snippet.${match[1]}` : 'snippet.txt'}
                isStreaming={false}
                autoPlay={false}
                showReplayButton={true}
                showCopyButton={true}
                showLanguageBadge={true}
                variant="dark"
              />
            </div>
          );
        },
        p: ({ children }) => <p className="mb-2 leading-relaxed last:mb-0 text-[1em] whitespace-pre-wrap">{children}</p>,
        a: ({ href, children }) => (
          <a href={href} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
            {children}
          </a>
        ),
        ul: ({ children }) => <ul className="list-disc pl-5 mb-4">{children}</ul>,
        ol: ({ children }) => <ol className="list-decimal pl-5 mb-4">{children}</ol>,
        li: ({ children }) => <li className="mb-1">{children}</li>,
        h1: ({ children }) => <h1 className="text-[2em] font-bold mt-6 mb-4">{children}</h1>,
        h2: ({ children }) => <h2 className="text-[1.5em] font-bold mt-5 mb-3">{children}</h2>,
        h3: ({ children }) => <h3 className="text-[1.17em] font-bold mt-4 mb-2">{children}</h3>,
        blockquote: ({ children }) => (
          <blockquote className="border-l-4 border-gray-300 dark:border-gray-600 pl-4 py-1 my-4 text-gray-600 dark:text-gray-400 italic bg-gray-50 dark:bg-gray-800/50 rounded-r-lg">
            {children}
          </blockquote>
        ),
        table: ({ children }) => (
          <div className="w-full overflow-x-auto my-5 border border-gray-200 dark:border-[#262626] rounded-lg bg-white dark:bg-[#141414] shadow-sm">
            <table className="w-full text-left border-collapse text-[13.5px]">{children}</table>
          </div>
        ),
        thead: ({ children }) => (
          <thead className="bg-gray-50 dark:bg-white/[0.05] border-b border-gray-200 dark:border-[#262626]">{children}</thead>
        ),
        tbody: ({ children }) => <tbody className="divide-y-0">{children}</tbody>,
        tr: ({ children }) => (
          <tr className="border-b border-gray-200 dark:border-[#262626] last:border-b-0 hover:bg-black/[0.02] dark:hover:bg-white/[0.02] transition-colors">
            {children}
          </tr>
        ),
        th: ({ children }) => (
          <th className="px-4 py-3 font-semibold text-gray-900 dark:text-white border-r border-gray-200 dark:border-[#262626] last:border-r-0 whitespace-nowrap tracking-tight bg-gray-50/80 dark:bg-white/[0.04]">
            {children}
          </th>
        ),
        td: ({ children }) => (
          <td className="px-4 py-3 text-gray-700 dark:text-[#d1cfca] border-r border-gray-200 dark:border-[#262626] last:border-r-0 align-middle tabular-nums whitespace-nowrap">
            {children}
          </td>
        ),
        strong: ({ children }) => <strong className="font-semibold text-gray-950 dark:text-white">{children}</strong>,
        em: ({ children }) => <em className="italic text-gray-800 dark:text-gray-200">{children}</em>,
        pre({ children }) {
          return <>{children}</>;
        },
      }}
    >
      {processedContent}
    </ReactMarkdown>
  );
};

export default MarkdownRenderer;
