import React, { useMemo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { AiCodeBlock } from '@/components/lightswind/ai-code-block';

/**
 * Remark plugin that identifies the active trailing token while streaming,
 * wrapping it in a frosted-stream-token container with a pulsating frosted cursor.
 * When the next token lands, the previous token settles into crisp text, creating
 * an ultra-smooth, organic blur-reveal effect.
 */
function createRemarkStreamingBlur(isStreaming) {
  return () => (tree) => {
    if (!isStreaming) return;
    let lastInfo = null;

    function walk(node, parent, index) {
      if (!node) return;
      if (node.type === 'text' && node.value && node.value.trim().length > 0) {
        lastInfo = { node, parent, index };
      }
      if (node.children) {
        for (let i = 0; i < node.children.length; i++) {
          walk(node.children[i], node, i);
        }
      }
    }

    walk(tree, null, -1);

    if (lastInfo && lastInfo.parent) {
      const val = lastInfo.node.value;
      const match = val.match(/^(.*?)(\S+\s*)$/s);
      if (match) {
        const lead = match[1];
        const trailing = match[2];
        const newNodes = [];

        if (lead) {
          newNodes.push({ type: 'text', value: lead });
        }

        // Active blurred token
        newNodes.push({
          type: 'paragraph',
          data: {
            hName: 'span',
            hProperties: { className: 'frosted-stream-token' },
          },
          children: [{ type: 'text', value: trailing }],
        });

        // Ambient frosted cursor
        newNodes.push({
          type: 'paragraph',
          data: {
            hName: 'span',
            hProperties: { className: 'frosted-stream-cursor', 'aria-hidden': 'true' },
          },
          children: [],
        });

        lastInfo.parent.children.splice(lastInfo.index, 1, ...newNodes);
      }
    }
  };
}

const MarkdownRenderer = ({ content, isStreaming = false }) => {
  // Pre-process HTML tags that might be generated by the AI since we don't have rehype-raw
  const processedContent = content
    ? content
        .replace(/<interactive_choice>[\s\S]*?(?:<\/interactive_choice>|$)/gi, '')
        .replace(/```(?:interactive-choice|interactive_choice)[\s\S]*?(?:```|$)/gi, '')
        .replace(/<br\s*\/?>/gi, '  \n') // convert <br> to markdown line break
        .replace(/<\/?b>/gi, '**')
        .replace(/<\/?strong>/gi, '**')
        .replace(/<\/?i>/gi, '*')
        .replace(/<\/?em>/gi, '*')
    : '';

  const remarkPlugins = useMemo(() => {
    return isStreaming
      ? [remarkGfm, createRemarkStreamingBlur(true)]
      : [remarkGfm];
  }, [isStreaming]);

  return (
    <ReactMarkdown
      remarkPlugins={remarkPlugins}
      components={{
        code({ className, children, ...props }) {
          const match = /language-(\w+)/.exec(className || '');
          const code = String(children).replace(/\n$/, '');
          
          // In react-markdown v9+, 'inline' prop is removed.
          // We consider it inline if it doesn't have a language match and doesn't contain multiple lines.
          const isInline = !match && !code.includes('\n');

          if (isInline) {
            return (
              <code
                className="rounded-[5px] bg-gray-100 dark:bg-white/[0.08] px-1.5 py-0.5 font-mono text-[12px] text-gray-800 dark:text-gray-200"
                {...props}
              >
                {children}
              </code>
            );
          }

          return (
            <div className="my-2.5">
              <AiCodeBlock
                code={code}
                language={match?.[1] || 'text'}
                filename={match?.[1] ? `snippet.${match[1]}` : 'snippet.txt'}
                isStreaming={false}
                autoPlay={false}
                showReplayButton={true}
                showCopyButton={true}
                showLanguageBadge={true}
                variant="dark"
              />
            </div>
          );
        },
        p: ({ children }) => <p className="mb-2 leading-[1.65] last:mb-0 text-[13.5px] whitespace-pre-wrap">{children}</p>,
        a: ({ href, children }) => (
          <a href={href} target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">
            {children}
          </a>
        ),
        ul: ({ children }) => <ul className="list-disc pl-4 mb-3 text-[13.5px] space-y-1">{children}</ul>,
        ol: ({ children }) => <ol className="list-decimal pl-4 mb-3 text-[13.5px] space-y-1">{children}</ol>,
        li: ({ children }) => <li className="leading-[1.6]">{children}</li>,
        h1: ({ children }) => <h1 className="text-[19px] font-bold mt-4 mb-2 tracking-tight text-gray-900 dark:text-white">{children}</h1>,
        h2: ({ children }) => <h2 className="text-[16px] font-semibold mt-3.5 mb-1.5 tracking-tight text-gray-900 dark:text-white">{children}</h2>,
        h3: ({ children }) => <h3 className="text-[14.5px] font-semibold mt-2.5 mb-1 tracking-tight text-gray-900 dark:text-white">{children}</h3>,
        blockquote: ({ children }) => (
          <blockquote className="border-l-3 border-gray-300 dark:border-gray-600 pl-3.5 py-0.5 my-3 text-[13px] text-gray-600 dark:text-gray-400 italic bg-gray-50/80 dark:bg-gray-800/40 rounded-r-md">
            {children}
          </blockquote>
        ),
        table: ({ children }) => (
          <div className="w-full overflow-x-auto my-3.5 border border-gray-200 dark:border-[#262626] rounded-lg bg-white dark:bg-[#141414] shadow-sm">
            <table className="w-full text-left border-collapse text-[12.5px]">{children}</table>
          </div>
        ),
        thead: ({ children }) => (
          <thead className="bg-gray-50 dark:bg-white/[0.05] border-b border-gray-200 dark:border-[#262626]">{children}</thead>
        ),
        tbody: ({ children }) => <tbody className="divide-y-0">{children}</tbody>,
        tr: ({ children }) => (
          <tr className="border-b border-gray-200 dark:border-[#262626] last:border-b-0 hover:bg-black/[0.02] dark:hover:bg-white/[0.02] transition-colors">
            {children}
          </tr>
        ),
        th: ({ children }) => (
          <th className="px-3.5 py-2 font-semibold text-gray-900 dark:text-white border-r border-gray-200 dark:border-[#262626] last:border-r-0 whitespace-nowrap tracking-tight bg-gray-50/80 dark:bg-white/[0.04]">
            {children}
          </th>
        ),
        td: ({ children }) => (
          <td className="px-3.5 py-2 text-gray-700 dark:text-[#d1cfca] border-r border-gray-200 dark:border-[#262626] last:border-r-0 align-middle tabular-nums whitespace-nowrap">
            {children}
          </td>
        ),
        strong: ({ children }) => <strong className="font-semibold text-gray-950 dark:text-white">{children}</strong>,
        em: ({ children }) => <em className="italic text-gray-800 dark:text-gray-200">{children}</em>,
        pre({ children }) {
          return <>{children}</>;
        },
      }}
    >
      {processedContent}
    </ReactMarkdown>
  );
};

export default MarkdownRenderer;
